#Requires -Version 7.0
Set-StrictMode -Version Latest

<#
.SYNOPSIS
    Interactive -Setup wizard. Collects connection + throughput settings and
    writes a .env file (secrets git-ignored).
.DESCRIPTION
    Prompts for tenant, client id, certificate thumbprint, destination site and
    throughput knobs, showing current values as defaults. Produces a .env in the
    layered format Import-SPOMigrationConfig consumes. Never echoes secrets back
    to logs. Returns the path to the written .env.
.EXAMPLE
    Show-SPOMigrationWizard -Path .env
#>
function Show-SPOMigrationWizard {
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([string])]
    param(
        [string] $Path = '.env',
        [pscustomobject] $Current,
        [hashtable] $Answers   # non-interactive override for tests/automation
    )

    if (-not $Current) {
        $Current = Import-SPOMigrationConfig -DotEnvPath $Path
    }

    # field spec: prompt text, env key, current value, secret?
    $fields = @(
        @{ Prompt = 'Tenant (contoso.onmicrosoft.com)'; Env = 'SPO_TENANT_ID';     Cur = $Current.TenantId }
        @{ Prompt = 'Entra App (client) id';            Env = 'SPO_CLIENT_ID';      Cur = $Current.ClientId }
        @{ Prompt = 'Certificate thumbprint';           Env = 'SPO_CERT_THUMBPRINT';Cur = $Current.Thumbprint; Secret = $true }
        @{ Prompt = 'Destination site URL';             Env = 'SPO_DEST_SITE_URL';  Cur = $Current.DestinationSiteUrl }
        @{ Prompt = 'Destination library';              Env = 'SPO_DEST_LIBRARY';   Cur = $Current.DestinationLibrary }
        @{ Prompt = 'Sites CSV path';                   Env = 'SPO_SITES_CSV';      Cur = $Current.SitesCsv }
        @{ Prompt = 'Concurrent sites (1-10)';          Env = 'SPO_SITE_THROTTLE';  Cur = $Current.SiteThrottle }
        @{ Prompt = 'Files per site (1-6)';             Env = 'SPO_FILE_THROTTLE';  Cur = $Current.FileThrottle }
        @{ Prompt = 'Tenant requests/sec ceiling';      Env = 'SPO_RPS';            Cur = $Current.RequestsPerSecond }
    )

    $collected = [ordered]@{}
    foreach ($f in $fields) {
        $default = [string]$f.Cur
        if ($Answers -and $Answers.ContainsKey($f.Env)) {
            $collected[$f.Env] = [string]$Answers[$f.Env]
            continue
        }
        $shownDefault = if ($f.Secret -and -not [string]::IsNullOrEmpty($default)) { '(unchanged)' } else { $default }
        $answer = Read-Host -Prompt ("{0} [{1}]" -f $f.Prompt, $shownDefault)
        if ([string]::IsNullOrWhiteSpace($answer)) {
            $collected[$f.Env] = $default
        }
        else {
            $collected[$f.Env] = $answer.Trim()
        }
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# SPOMigrate configuration — generated by Show-SPOMigrationWizard')
    $lines.Add('# This file is git-ignored. Never commit real secrets.')
    $lines.Add(('# Generated {0}' -f ([DateTime]::UtcNow.ToString('u'))))
    $lines.Add('')
    foreach ($kv in $collected.GetEnumerator()) {
        $val = [string]$kv.Value
        if ($val -match '\s') { $val = '"' + $val + '"' }
        $lines.Add(('{0}={1}' -f $kv.Key, $val))
    }

    if ($PSCmdlet.ShouldProcess($Path, 'Write .env')) {
        Set-Content -LiteralPath $Path -Value $lines -Encoding utf8
        Write-Host "Wrote configuration to $Path" -ForegroundColor Green
    }
    $Path
}
